[project]
name = "tubes-1-ai"
version = "0.1.0"
description = "Tugas Besar 1 AI"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "viser>=1.1.1",
]

[project.scripts]
# hello-world = "hello_world:main" --> ganti jadi test scripts

[tool.hatch.build.targets.wheel]
packages = ["src"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
